### ISSUE TITLE
Failed to launch smithy extension probably because cs launch command does not work properly

### ISSUE THREAD

**Issue by i10416** [disneystreaming/vscode-smithy#21]
vs code smithy extension failed to launch due to the following error. I'm not sure if this repository is the right place to post error report. If there's better one, please tell me.

```
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM adopt@1.8+ not found in index: JVM adopt not found
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
[Error - 10:18:14 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:18:14 PM] The Smithy LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:18:14 PM] Smithy LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:18:14 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

It seems coursier failed to download adopt@1.8+. In fact, my local coursier cannot download java with 8 or 1.8 identifier.

```sh
cs version
2.1.3
cs java --jvm 1.8+                                                                                                                   ~
JVM 1.8+ not found in index: No adoptium version matching '1.8+' found

cs java --jvm 8+                                                                                                                     ~
JVM 8+ not found in index: No adoptium version matching '1.8+' found

cs java --jvm 11+
// It works and starts downloading jvm

```

```
cs launch software.amazon.smithy:smithy-language-server:0.2.3                                                                        ~
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM adopt@1.8+ not found in index: JVM adopt not found
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by i10416** [comment]
This error probably comes from coursier and M1 Mac combination...

https://github.com/coursier/coursier/issues/2537

**Comment by i10416** [comment]
`cs launch --jvm 11 software.amazon.smithy:smithy-language-server:0.2.3` works.

**Comment by daddykotex** [comment]
Thanks for reporting. I'm sort of surprised this is happening.

A few questions:
1. did you have a JVM on your machine prior to installing / executing the extension?
2. did you have `cs` or `coursier` on your machine prior to installing / executing the extension?

We don't try to install a JVM, we sort of assume there is one, so I guess what is happening is the following:
1. the extension uses `coursier` to start the server
2. `coursier` thinks there is no JVM on the system (maybe there is not) so it tries to install it
3. it fails to because the combination of os/version choose to install a version that is not in the default index

**Comment by i10416** [comment]
> 1. did you have a JVM on your machine prior to installing / executing the extension?
Yes, but I installed JVM via nix home-manager, which may be the culprit.

> 2. did you have cs or coursier on your machine prior to installing / executing the extension?
Yes.

**Comment by i10416** [comment]
`JAVA_HOME=/path/to/java/home cs launch software.amazon.smithy:smithy-language-server:0.2.3` also works.

**Comment by i10416** [comment]
So, the question is how I can pass JAVA_HOME or jvm version to coursier. 
 
I tried the .vscode/settings.json, but in vain. This is presumably because the environment where coursier is running is different from the terminal. It seems vscode extension launches coursier as a separate process.

```
{
    "files.watcherExclude": {
        "**/target": true
    },
    "terminal.integrated.env.osx": {
        "JAVA_HOME": "/my/java/home"
    },
    "terminal.integrated.env.linux": {
        "JAVA_HOME": "/my/java/home"
      }
}
```

**Comment by i10416** [comment]
Can we forward user JAVA_HOME here like?

https://github.com/disneystreaming/vscode-smithy/blob/af1e1e7f5389cd6db481b5bbbebc6db6bbcc3120/src/extension.ts#L89

**Comment by daddykotex** [comment]
This is definitely possible: 

```
    const startServer = {
      command: csBinaryPath,
      args,
      options: { env: { JAVA_HOME: process.env["JAVA_HOME"] } },
    };
```

is valid code so that could work.

**Comment by daddykotex** [comment]
thanks to you, pretty sure this will be helpful to others

**Comment by kubukoz** [comment]
missed this the first time but I see there's another Nix user here :D 

there's dozens of us!
